CREATE TABLE transactions (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 user_id INTEGER NOT NULL, symbol TEXT NOT NULL, shares INTEGER NOT NULL,
 price REAL NOT NULL,timestamp TEXT NOT NULL,type TEXT NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id))